export const GLOBAL_VARS = {
    TX_INPUT_BASE: 32 + 4 + 1 + 4,
    TX_SCRIPTSIG: 139,
    TX_OUTPUT_BASE: 8 + 1,
    TX_OUTPUT_PUBKEYHASH: 25,
    TX_EMPTY_SIZE: 4 + 1 + 1 + 4,
    HASH_TYPE: 0x01,
    MAX_FEE_RATE: 0.4,
    AVG_FEE_RATE: 0.002,
    CONTRACT_CALL: 1,
    CONTRACT_CREATION: 2,
    P2PKH: 3,
    DEPLOY_ERROR: 4,
    UTXO_VINDEX: 0
  }
  